word = input(str('Type Text ---> ')).lower()

try:
    word = word.replace(' ',' / ')
    word = word.replace('a','.- ')
    word = word.replace('b','.-... ')
    word = word.replace('c','-.-.')
    word = word.replace('d','-.. ')
    word = word.replace('e','. ')
    word = word.replace('f','..-. ')
    word = word.replace('g','--. ')
    word = word.replace('h','.... ')
    word = word.replace('i','.. ')
    word = word.replace('j','.--- ')
    word = word.replace('k','-.- ')
    word = word.replace('l','.-.. ')
    word = word.replace('m','-- ')
    word = word.replace('n','-. ')
    word = word.replace('o','--- ')
    word = word.replace('p','.--. ')
    word = word.replace('q','--.- ')
    word = word.replace('r','.-. ')
    word = word.replace('s','... ')
    word = word.replace('t','- ')
    word = word.replace('u','..- ')
    word = word.replace('v','...- ')
    word = word.replace('w','.-- ')
    word = word.replace('x','-..- ')
    word = word.replace('y','-.-- ')
    word = word.replace('z','--.. ')

    word = word.replace('0','----- ')
    word = word.replace('1','.---- ')
    word = word.replace('2','..--- ')
    word = word.replace('3','...-- ')
    word = word.replace('4','....- ')
    word = word.replace('5','..... ')
    word = word.replace('6','-.... ')
    word = word.replace('7','--... ')
    word = word.replace('8','---.. ')
    word = word.replace('9','----. ')

    print(word)

except:
    print('\n Error !')
